export const data=[
    {  imgUrl:"https://tse3.mm.bing.net/th?id=OIP.WuYEGgz6L82X0Lj2J9GunQHaHa&pid=Api&P=0&w=175&h=175",
        title:"dark ",
        description:"netflix series",
        bt:"Watch Now",
        rate:5,
        id : 1,
        video:"https://www.youtube.com/embed/U_1XXdXEKgI",
        topic:"Un agent du gouvernement doit traquer et tuer un terroriste avant qu'il ne perde sa mémoire à cause de la démence Réalisation",
      },
      { imgUrl:"https://tse1.mm.bing.net/th?id=OIP.jsSnvX9P6xmwbnuznluM8AHaK-&pid=Api&P=0&w=119&h=177",
        title:"Extra Currucular ",
        description:" netflix series",
        bt:"Watch Now",
        rate:4,
        id : 2,
        video:"https://www.youtube.com/embed/U_1XXdXEKgI",
        topic:"Un agent du gouvernement doit traquer et tuer un terroriste avant qu'il ne perde sa mémoire à cause de la démence Réalisation",
      },
       {imgUrl:"https://tse3.mm.bing.net/th?id=OIP.AvfIrRRX1kkvfvOVCjxXCAHaK-&pid=Api&P=0&w=116&h=171",
        title:"Stranger Things",
        description:" netflix series",
        bt:"Watch Now",
        rate:3,
        id:3,
        video:"https://www.youtube.com/embed/U_1XXdXEKgI",
        topic:"Un agent du gouvernement doit traquer et tuer un terroriste avant qu'il ne perde sa mémoire à cause de la démence Réalisation",
      },
      { imgUrl:"https://tse3.mm.bing.net/th?id=OIP.1PeEnNKbbOIAAcnpFsqI2AHaEK&pid=Api&P=0&w=327&h=184",
        title:"Vampire Diaries",
        description:" netflix series",
        bt:"Watch Now",
        rate:3,
        id:4,
        video:"https://www.youtube.com/embed/U_1XXdXEKgI",
        topic:"Un agent du gouvernement doit traquer et tuer un terroriste avant qu'il ne perde sa mémoire à cause de la démence Réalisation",
      },
      { imgUrl:"https://tse2.mm.bing.net/th?id=OIP.vIcBMg50Zi3wBeehA-YPRQHaEK&pid=Api&P=0&w=325&h=182",
        title:"My First Love",
        description:" netflix series",
        bt:"Watch Now",
        rate:2,
        id:5,
        video:"https://www.youtube.com/embed/U_1XXdXEKgI",
        topic:"Un agent du gouvernement doit traquer et tuer un terroriste avant qu'il ne perde sa mémoire à cause de la démence Réalisation",
      },
     {
        imgUrl:"https://tse4.mm.bing.net/th?id=OIF.XqLgxCeui60YvC7YMmk89Q&pid=Api&P=0&w=169&h=95",
        title:"Squid Game",
        description:" netflix series",
        bt:"Watch Now",
        rate:2,
        id:6,
        video:"https://www.youtube.com/embed/U_1XXdXEKgI",
        topic:"Un agent du gouvernement doit traquer et tuer un terroriste avant qu'il ne perde sa mémoire à cause de la démence Réalisation",
      },
]